name: Validate PR/merge
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
      - uses: actions/checkout@v2
      - run: |
        dotnet tool restore
        dotnet csharpier --check .
