/*
 * ePayment API
 *
 * The ePayment API enables you to create Vipps MobilePay payments for online and in-person payments. See the [ePayment API Guide](https://developer.vippsmobilepay.com/docs/APIs/epayment-api) for more details.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vipps.net.Models.Epayment.Client.OpenAPIDateConverter;

namespace Vipps.net.Models.Epayment.Model
{
    /// <summary>
    /// PaymentAdjustment
    /// </summary>
    [DataContract(Name = "PaymentAdjustment")]
    public partial class PaymentAdjustment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentAdjustment" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PaymentAdjustment() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentAdjustment" /> class.
        /// </summary>
        /// <param name="modificationAmount">modificationAmount (required).</param>
        /// <param name="modificationReference">The &#x60;reference&#x60; is the unique identifier for the payment, specified when initiating the payment. The reference must be unique for the sales unit (MSN), but is not _globally_ unique, so several MSNs may use the same reference. See the [recommendations](/docs/knowledge-base/orderid/). (required).</param>
        public PaymentAdjustment(Amount modificationAmount = default(Amount), string modificationReference = default(string))
        {
            // to ensure "modificationAmount" is required (not null)
            if (modificationAmount == null)
            {
                throw new ArgumentNullException("modificationAmount is a required property for PaymentAdjustment and cannot be null");
            }
            this.ModificationAmount = modificationAmount;
            // to ensure "modificationReference" is required (not null)
            if (modificationReference == null)
            {
                throw new ArgumentNullException("modificationReference is a required property for PaymentAdjustment and cannot be null");
            }
            this.ModificationReference = modificationReference;
        }

        /// <summary>
        /// Gets or Sets ModificationAmount
        /// </summary>
        [DataMember(Name = "modificationAmount", IsRequired = true, EmitDefaultValue = true)]
        public Amount ModificationAmount { get; set; }

        /// <summary>
        /// The &#x60;reference&#x60; is the unique identifier for the payment, specified when initiating the payment. The reference must be unique for the sales unit (MSN), but is not _globally_ unique, so several MSNs may use the same reference. See the [recommendations](/docs/knowledge-base/orderid/).
        /// </summary>
        /// <value>The &#x60;reference&#x60; is the unique identifier for the payment, specified when initiating the payment. The reference must be unique for the sales unit (MSN), but is not _globally_ unique, so several MSNs may use the same reference. See the [recommendations](/docs/knowledge-base/orderid/).</value>
        /*
        <example>acme-shop-123-order123abc</example>
        */
        [DataMember(Name = "modificationReference", IsRequired = true, EmitDefaultValue = true)]
        public string ModificationReference { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentAdjustment {\n");
            sb.Append("  ModificationAmount: ").Append(ModificationAmount).Append("\n");
            sb.Append("  ModificationReference: ").Append(ModificationReference).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ModificationReference (string) maxLength
            if (this.ModificationReference != null && this.ModificationReference.Length > 50)
            {
                yield return new ValidationResult("Invalid value for ModificationReference, length must be less than 50.", new [] { "ModificationReference" });
            }

            // ModificationReference (string) minLength
            if (this.ModificationReference != null && this.ModificationReference.Length < 8)
            {
                yield return new ValidationResult("Invalid value for ModificationReference, length must be greater than 8.", new [] { "ModificationReference" });
            }

            if (this.ModificationReference != null) {
                // ModificationReference (string) pattern
                Regex regexModificationReference = new Regex(@"^[a-zA-Z0-9-]{8,50}$", RegexOptions.CultureInvariant);
                if (!regexModificationReference.Match(this.ModificationReference).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ModificationReference, must match a pattern of " + regexModificationReference, new [] { "ModificationReference" });
                }
            }

            yield break;
        }
    }

}
