/*
 * ePayment API
 *
 * The ePayment API enables you to create Vipps MobilePay payments for online and in-person payments. See the [ePayment API Guide](https://developer.vippsmobilepay.com/docs/APIs/epayment-api) for more details.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vipps.net.Models.Epayment.Client.OpenAPIDateConverter;

namespace Vipps.net.Models.Epayment.Model
{
    /// <summary>
    /// ProfileResponse
    /// </summary>
    [DataContract(Name = "ProfileResponse")]
    public partial class ProfileResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileResponse" /> class.
        /// </summary>
        /// <param name="sub">If &#x60;profile.scope&#x60; was requested in &#x60;createPayment&#x60;, this value will be populated once &#x60;state&#x60; is &#x60;AUTHORIZED&#x60;. This can be used towards the [Userinfo endpoint](https://developer.vippsmobilepay.com/api/userinfo#operation/getUserinfo) to fetch required user data..</param>
        public ProfileResponse(string sub = default(string))
        {
            this.Sub = sub;
        }

        /// <summary>
        /// If &#x60;profile.scope&#x60; was requested in &#x60;createPayment&#x60;, this value will be populated once &#x60;state&#x60; is &#x60;AUTHORIZED&#x60;. This can be used towards the [Userinfo endpoint](https://developer.vippsmobilepay.com/api/userinfo#operation/getUserinfo) to fetch required user data.
        /// </summary>
        /// <value>If &#x60;profile.scope&#x60; was requested in &#x60;createPayment&#x60;, this value will be populated once &#x60;state&#x60; is &#x60;AUTHORIZED&#x60;. This can be used towards the [Userinfo endpoint](https://developer.vippsmobilepay.com/api/userinfo#operation/getUserinfo) to fetch required user data.</value>
        [DataMember(Name = "sub", EmitDefaultValue = false)]
        public string Sub { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProfileResponse {\n");
            sb.Append("  Sub: ").Append(Sub).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
