/*
 * checkout-backend-merchant-v3.API
 *
 * See the [Checkout API Guide](https://developer.vippsmobilepay.com/docs/APIs/checkout-api/).
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vipps.net.Models.Checkout.Client.OpenAPIDateConverter;

namespace Vipps.net.Models.Checkout.Model
{
    /// <summary>
    /// EventSubscriptionCampaign
    /// </summary>
    [DataContract(Name = "EventSubscriptionCampaign")]
    public partial class EventSubscriptionCampaign : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventSubscriptionCampaign" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EventSubscriptionCampaign() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EventSubscriptionCampaign" /> class.
        /// </summary>
        /// <param name="eventDate">eventDate (required).</param>
        /// <param name="eventText">eventText (required).</param>
        /// <param name="type">type (required) (default to &quot;EVENT_CAMPAIGN&quot;).</param>
        /// <param name="price">price (required).</param>
        public EventSubscriptionCampaign(string eventDate = default(string), string eventText = default(string), string type = @"EVENT_CAMPAIGN", int price = default(int))
        {
            // to ensure "eventDate" is required (not null)
            if (eventDate == null)
            {
                throw new ArgumentNullException("eventDate is a required property for EventSubscriptionCampaign and cannot be null");
            }
            this.EventDate = eventDate;
            // to ensure "eventText" is required (not null)
            if (eventText == null)
            {
                throw new ArgumentNullException("eventText is a required property for EventSubscriptionCampaign and cannot be null");
            }
            this.EventText = eventText;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for EventSubscriptionCampaign and cannot be null");
            }
            this.Type = type;
            this.Price = price;
        }

        /// <summary>
        /// Gets or Sets EventDate
        /// </summary>
        [DataMember(Name = "eventDate", IsRequired = true, EmitDefaultValue = true)]
        public string EventDate { get; set; }

        /// <summary>
        /// Gets or Sets EventText
        /// </summary>
        [DataMember(Name = "eventText", IsRequired = true, EmitDefaultValue = true)]
        public string EventText { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Price
        /// </summary>
        [DataMember(Name = "price", IsRequired = true, EmitDefaultValue = true)]
        public int Price { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventSubscriptionCampaign {\n");
            sb.Append("  EventDate: ").Append(EventDate).Append("\n");
            sb.Append("  EventText: ").Append(EventText).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // EventDate (string) minLength
            if (this.EventDate != null && this.EventDate.Length < 1)
            {
                yield return new ValidationResult("Invalid value for EventDate, length must be greater than 1.", new [] { "EventDate" });
            }

            // EventText (string) maxLength
            if (this.EventText != null && this.EventText.Length > 15)
            {
                yield return new ValidationResult("Invalid value for EventText, length must be less than 15.", new [] { "EventText" });
            }

            // EventText (string) minLength
            if (this.EventText != null && this.EventText.Length < 1)
            {
                yield return new ValidationResult("Invalid value for EventText, length must be greater than 1.", new [] { "EventText" });
            }

            if (this.Type != null) {
                // Type (string) pattern
                Regex regexType = new Regex(@"EVENT_CAMPAIGN", RegexOptions.CultureInvariant);
                if (!regexType.Match(this.Type).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Type, must match a pattern of " + regexType, new [] { "Type" });
                }
            }

            // Price (int) minimum
            if (this.Price < (int)0)
            {
                yield return new ValidationResult("Invalid value for Price, must be a value greater than or equal to 0.", new [] { "Price" });
            }

            yield break;
        }
    }

}
