/*
 * checkout-backend-merchant-v3.API
 *
 * See the [Checkout API Guide](https://developer.vippsmobilepay.com/docs/APIs/checkout-api/).
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vipps.net.Models.Checkout.Client.OpenAPIDateConverter;

namespace Vipps.net.Models.Checkout.Model
{
    /// <summary>
    /// Request to set up a Recurring Checkout session
    /// </summary>
    [DataContract(Name = "InitiateSubscriptionSessionRequest")]
    public partial class InitiateSubscriptionSessionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InitiateSubscriptionSessionRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InitiateSubscriptionSessionRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InitiateSubscriptionSessionRequest" /> class.
        /// </summary>
        /// <param name="reference">Required when no Transaction is present. This is the merchant&#39;s unique reference to the Checkout Session (as well as the optional payment transaction).</param>
        /// <param name="transaction">Defines a one-time-payment.</param>
        /// <param name="subscription">Defines a subscription. Used for future payments. (required).</param>
        /// <param name="type">type (required) (default to &quot;SUBSCRIPTION&quot;).</param>
        /// <param name="prefillCustomer">Information about the customer to be prefilled                If any of the customer information is invalid such as the phone number,  the customer will be prompted to input new user information..</param>
        /// <param name="merchantInfo">merchantInfo (required).</param>
        /// <param name="varConfiguration">varConfiguration.</param>
        public InitiateSubscriptionSessionRequest(string reference = default(string), PaymentTransaction transaction = default(PaymentTransaction), Subscription subscription = default(Subscription), string type = @"SUBSCRIPTION", PrefillCustomer prefillCustomer = default(PrefillCustomer), MerchantInfo merchantInfo = default(MerchantInfo), CheckoutConfig varConfiguration = default(CheckoutConfig))
        {
            // to ensure "subscription" is required (not null)
            if (subscription == null)
            {
                throw new ArgumentNullException("subscription is a required property for InitiateSubscriptionSessionRequest and cannot be null");
            }
            this.Subscription = subscription;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for InitiateSubscriptionSessionRequest and cannot be null");
            }
            this.Type = type;
            // to ensure "merchantInfo" is required (not null)
            if (merchantInfo == null)
            {
                throw new ArgumentNullException("merchantInfo is a required property for InitiateSubscriptionSessionRequest and cannot be null");
            }
            this.MerchantInfo = merchantInfo;
            this.Reference = reference;
            this.Transaction = transaction;
            this.PrefillCustomer = prefillCustomer;
            this.VarConfiguration = varConfiguration;
        }

        /// <summary>
        /// Required when no Transaction is present. This is the merchant&#39;s unique reference to the Checkout Session (as well as the optional payment transaction)
        /// </summary>
        /// <value>Required when no Transaction is present. This is the merchant&#39;s unique reference to the Checkout Session (as well as the optional payment transaction)</value>
        [DataMember(Name = "reference", EmitDefaultValue = true)]
        public string Reference { get; set; }

        /// <summary>
        /// Defines a one-time-payment
        /// </summary>
        /// <value>Defines a one-time-payment</value>
        [DataMember(Name = "transaction", EmitDefaultValue = true)]
        public PaymentTransaction Transaction { get; set; }

        /// <summary>
        /// Defines a subscription. Used for future payments.
        /// </summary>
        /// <value>Defines a subscription. Used for future payments.</value>
        [DataMember(Name = "subscription", IsRequired = true, EmitDefaultValue = true)]
        public Subscription Subscription { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Information about the customer to be prefilled                If any of the customer information is invalid such as the phone number,  the customer will be prompted to input new user information.
        /// </summary>
        /// <value>Information about the customer to be prefilled                If any of the customer information is invalid such as the phone number,  the customer will be prompted to input new user information.</value>
        [DataMember(Name = "prefillCustomer", EmitDefaultValue = true)]
        public PrefillCustomer PrefillCustomer { get; set; }

        /// <summary>
        /// Gets or Sets MerchantInfo
        /// </summary>
        [DataMember(Name = "merchantInfo", IsRequired = true, EmitDefaultValue = true)]
        public MerchantInfo MerchantInfo { get; set; }

        /// <summary>
        /// Gets or Sets VarConfiguration
        /// </summary>
        [DataMember(Name = "configuration", EmitDefaultValue = true)]
        public CheckoutConfig VarConfiguration { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InitiateSubscriptionSessionRequest {\n");
            sb.Append("  Reference: ").Append(Reference).Append("\n");
            sb.Append("  Transaction: ").Append(Transaction).Append("\n");
            sb.Append("  Subscription: ").Append(Subscription).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  PrefillCustomer: ").Append(PrefillCustomer).Append("\n");
            sb.Append("  MerchantInfo: ").Append(MerchantInfo).Append("\n");
            sb.Append("  VarConfiguration: ").Append(VarConfiguration).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.Type != null) {
                // Type (string) pattern
                Regex regexType = new Regex(@"SUBSCRIPTION", RegexOptions.CultureInvariant);
                if (!regexType.Match(this.Type).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Type, must match a pattern of " + regexType, new [] { "Type" });
                }
            }

            yield break;
        }
    }

}
