/*
 * ePayment API
 *
 * The ePayment API enables you to create Vipps MobilePay payments for online and in-person payments. See the [ePayment API Guide](https://developer.vippsmobilepay.com/docs/APIs/epayment-api) for more details.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Epayment.Model;
using Vipps.net.Models.Epayment.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Epayment.Test.Model
{
    /// <summary>
    ///  Class for testing Aggregate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AggregateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Aggregate
        //private Aggregate instance;

        public AggregateTests()
        {
            // TODO uncomment below to create an instance of Aggregate
            //instance = new Aggregate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Aggregate
        /// </summary>
        [Fact]
        public void AggregateInstanceTest()
        {
            // TODO uncomment below to test "IsType" Aggregate
            //Assert.IsType<Aggregate>(instance);
        }

        /// <summary>
        /// Test the property 'AuthorizedAmount'
        /// </summary>
        [Fact]
        public void AuthorizedAmountTest()
        {
            // TODO unit test for the property 'AuthorizedAmount'
        }

        /// <summary>
        /// Test the property 'CancelledAmount'
        /// </summary>
        [Fact]
        public void CancelledAmountTest()
        {
            // TODO unit test for the property 'CancelledAmount'
        }

        /// <summary>
        /// Test the property 'CapturedAmount'
        /// </summary>
        [Fact]
        public void CapturedAmountTest()
        {
            // TODO unit test for the property 'CapturedAmount'
        }

        /// <summary>
        /// Test the property 'RefundedAmount'
        /// </summary>
        [Fact]
        public void RefundedAmountTest()
        {
            // TODO unit test for the property 'RefundedAmount'
        }
    }
}
