/*
 * ePayment API
 *
 * The ePayment API enables you to create Vipps MobilePay payments for online and in-person payments. See the [ePayment API Guide](https://developer.vippsmobilepay.com/docs/APIs/epayment-api) for more details.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Epayment.Model;
using Vipps.net.Models.Epayment.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Epayment.Test.Model
{
    /// <summary>
    ///  Class for testing CancelModificationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CancelModificationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CancelModificationRequest
        //private CancelModificationRequest instance;

        public CancelModificationRequestTests()
        {
            // TODO uncomment below to create an instance of CancelModificationRequest
            //instance = new CancelModificationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CancelModificationRequest
        /// </summary>
        [Fact]
        public void CancelModificationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CancelModificationRequest
            //Assert.IsType<CancelModificationRequest>(instance);
        }

        /// <summary>
        /// Test the property 'CancelTransactionOnly'
        /// </summary>
        [Fact]
        public void CancelTransactionOnlyTest()
        {
            // TODO unit test for the property 'CancelTransactionOnly'
        }
    }
}
