/*
 * ePayment API
 *
 * The ePayment API enables you to create Vipps MobilePay payments for online and in-person payments. See the [ePayment API Guide](https://developer.vippsmobilepay.com/docs/APIs/epayment-api) for more details.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Epayment.Model;
using Vipps.net.Models.Epayment.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Epayment.Test.Model
{
    /// <summary>
    ///  Class for testing Customer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Customer
        //private Customer instance;

        public CustomerTests()
        {
            // TODO uncomment below to create an instance of Customer
            //instance = new Customer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Customer
        /// </summary>
        [Fact]
        public void CustomerInstanceTest()
        {
            // TODO uncomment below to test "IsType" Customer
            //Assert.IsType<Customer>(instance);
        }

        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

        /// <summary>
        /// Test the property 'PersonalQr'
        /// </summary>
        [Fact]
        public void PersonalQrTest()
        {
            // TODO unit test for the property 'PersonalQr'
        }

        /// <summary>
        /// Test the property 'CustomerToken'
        /// </summary>
        [Fact]
        public void CustomerTokenTest()
        {
            // TODO unit test for the property 'CustomerToken'
        }
    }
}
