/*
 * ePayment API
 *
 * The ePayment API enables you to create Vipps MobilePay payments for online and in-person payments. See the [ePayment API Guide](https://developer.vippsmobilepay.com/docs/APIs/epayment-api) for more details.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Epayment.Model;
using Vipps.net.Models.Epayment.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Epayment.Test.Model
{
    /// <summary>
    ///  Class for testing ForceApprove
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ForceApproveTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ForceApprove
        //private ForceApprove instance;

        public ForceApproveTests()
        {
            // TODO uncomment below to create an instance of ForceApprove
            //instance = new ForceApprove();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ForceApprove
        /// </summary>
        [Fact]
        public void ForceApproveInstanceTest()
        {
            // TODO uncomment below to test "IsType" ForceApprove
            //Assert.IsType<ForceApprove>(instance);
        }

        /// <summary>
        /// Test the property 'Customer'
        /// </summary>
        [Fact]
        public void CustomerTest()
        {
            // TODO unit test for the property 'Customer'
        }

        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
    }
}
