/*
 * ePayment API
 *
 * The ePayment API enables you to create Vipps MobilePay payments for online and in-person payments. See the [ePayment API Guide](https://developer.vippsmobilepay.com/docs/APIs/epayment-api) for more details.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Epayment.Model;
using Vipps.net.Models.Epayment.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Epayment.Test.Model
{
    /// <summary>
    ///  Class for testing ModificationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModificationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModificationResponse
        //private ModificationResponse instance;

        public ModificationResponseTests()
        {
            // TODO uncomment below to create an instance of ModificationResponse
            //instance = new ModificationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModificationResponse
        /// </summary>
        [Fact]
        public void ModificationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModificationResponse
            //Assert.IsType<ModificationResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Aggregate'
        /// </summary>
        [Fact]
        public void AggregateTest()
        {
            // TODO unit test for the property 'Aggregate'
        }

        /// <summary>
        /// Test the property 'PspReference'
        /// </summary>
        [Fact]
        public void PspReferenceTest()
        {
            // TODO unit test for the property 'PspReference'
        }

        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
    }
}
