/*
 * ePayment API
 *
 * The ePayment API enables you to create Vipps MobilePay payments for online and in-person payments. See the [ePayment API Guide](https://developer.vippsmobilepay.com/docs/APIs/epayment-api) for more details.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Epayment.Model;
using Vipps.net.Models.Epayment.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Epayment.Test.Model
{
    /// <summary>
    ///  Class for testing Receipt
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReceiptTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Receipt
        //private Receipt instance;

        public ReceiptTests()
        {
            // TODO uncomment below to create an instance of Receipt
            //instance = new Receipt();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Receipt
        /// </summary>
        [Fact]
        public void ReceiptInstanceTest()
        {
            // TODO uncomment below to test "IsType" Receipt
            //Assert.IsType<Receipt>(instance);
        }

        /// <summary>
        /// Test the property 'OrderLines'
        /// </summary>
        [Fact]
        public void OrderLinesTest()
        {
            // TODO unit test for the property 'OrderLines'
        }

        /// <summary>
        /// Test the property 'BottomLine'
        /// </summary>
        [Fact]
        public void BottomLineTest()
        {
            // TODO unit test for the property 'BottomLine'
        }
    }
}
