/*
 * ePayment API
 *
 * The ePayment API enables you to create Vipps MobilePay payments for online and in-person payments. See the [ePayment API Guide](https://developer.vippsmobilepay.com/docs/APIs/epayment-api) for more details.
 *
 * The version of the OpenAPI document: 1.6.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Epayment.Model;
using Vipps.net.Models.Epayment.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Epayment.Test.Model
{
    /// <summary>
    ///  Class for testing ShippingInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShippingInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShippingInfo
        //private ShippingInfo instance;

        public ShippingInfoTests()
        {
            // TODO uncomment below to create an instance of ShippingInfo
            //instance = new ShippingInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShippingInfo
        /// </summary>
        [Fact]
        public void ShippingInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShippingInfo
            //Assert.IsType<ShippingInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'AmountExcludingTax'
        /// </summary>
        [Fact]
        public void AmountExcludingTaxTest()
        {
            // TODO unit test for the property 'AmountExcludingTax'
        }

        /// <summary>
        /// Test the property 'TaxAmount'
        /// </summary>
        [Fact]
        public void TaxAmountTest()
        {
            // TODO unit test for the property 'TaxAmount'
        }

        /// <summary>
        /// Test the property 'TaxPercentage'
        /// </summary>
        [Fact]
        public void TaxPercentageTest()
        {
            // TODO unit test for the property 'TaxPercentage'
        }
    }
}
