/*
 * checkout-backend-merchant-v3.API
 *
 * See the [Checkout API Guide](https://developer.vippsmobilepay.com/docs/APIs/checkout-api/).
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Checkout.Model;
using Vipps.net.Models.Checkout.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Checkout.Test.Model
{
    /// <summary>
    ///  Class for testing CheckoutSessionThirdPartyInformationHeaders
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckoutSessionThirdPartyInformationHeadersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CheckoutSessionThirdPartyInformationHeaders
        //private CheckoutSessionThirdPartyInformationHeaders instance;

        public CheckoutSessionThirdPartyInformationHeadersTests()
        {
            // TODO uncomment below to create an instance of CheckoutSessionThirdPartyInformationHeaders
            //instance = new CheckoutSessionThirdPartyInformationHeaders();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckoutSessionThirdPartyInformationHeaders
        /// </summary>
        [Fact]
        public void CheckoutSessionThirdPartyInformationHeadersInstanceTest()
        {
            // TODO uncomment below to test "IsType" CheckoutSessionThirdPartyInformationHeaders
            //Assert.IsType<CheckoutSessionThirdPartyInformationHeaders>(instance);
        }

        /// <summary>
        /// Test the property 'VippsSystemName'
        /// </summary>
        [Fact]
        public void VippsSystemNameTest()
        {
            // TODO unit test for the property 'VippsSystemName'
        }

        /// <summary>
        /// Test the property 'VippsSystemVersion'
        /// </summary>
        [Fact]
        public void VippsSystemVersionTest()
        {
            // TODO unit test for the property 'VippsSystemVersion'
        }

        /// <summary>
        /// Test the property 'VippsSystemPluginName'
        /// </summary>
        [Fact]
        public void VippsSystemPluginNameTest()
        {
            // TODO unit test for the property 'VippsSystemPluginName'
        }

        /// <summary>
        /// Test the property 'VippsSystemPluginVersion'
        /// </summary>
        [Fact]
        public void VippsSystemPluginVersionTest()
        {
            // TODO unit test for the property 'VippsSystemPluginVersion'
        }
    }
}
