/*
 * checkout-backend-merchant-v3.API
 *
 * See the [Checkout API Guide](https://developer.vippsmobilepay.com/docs/APIs/checkout-api/).
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Checkout.Model;
using Vipps.net.Models.Checkout.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Checkout.Test.Model
{
    /// <summary>
    ///  Class for testing Helthjem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HelthjemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Helthjem
        //private Helthjem instance;

        public HelthjemTests()
        {
            // TODO uncomment below to create an instance of Helthjem
            //instance = new Helthjem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Helthjem
        /// </summary>
        [Fact]
        public void HelthjemInstanceTest()
        {
            // TODO uncomment below to test "IsType" Helthjem
            //Assert.IsType<Helthjem>(instance);
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'ShopId'
        /// </summary>
        [Fact]
        public void ShopIdTest()
        {
            // TODO unit test for the property 'ShopId'
        }
    }
}
