/*
 * checkout-backend-merchant-v3.API
 *
 * See the [Checkout API Guide](https://developer.vippsmobilepay.com/docs/APIs/checkout-api/).
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Checkout.Model;
using Vipps.net.Models.Checkout.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Checkout.Test.Model
{
    /// <summary>
    ///  Class for testing IdempotencyHeader
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdempotencyHeaderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdempotencyHeader
        //private IdempotencyHeader instance;

        public IdempotencyHeaderTests()
        {
            // TODO uncomment below to create an instance of IdempotencyHeader
            //instance = new IdempotencyHeader();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdempotencyHeader
        /// </summary>
        [Fact]
        public void IdempotencyHeaderInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdempotencyHeader
            //Assert.IsType<IdempotencyHeader>(instance);
        }

        /// <summary>
        /// Test the property 'IdempotencyKey'
        /// </summary>
        [Fact]
        public void IdempotencyKeyTest()
        {
            // TODO unit test for the property 'IdempotencyKey'
        }
    }
}
