/*
 * checkout-backend-merchant-v3.API
 *
 * See the [Checkout API Guide](https://developer.vippsmobilepay.com/docs/APIs/checkout-api/).
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Checkout.Model;
using Vipps.net.Models.Checkout.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Checkout.Test.Model
{
    /// <summary>
    ///  Class for testing InitiateSessionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InitiateSessionResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InitiateSessionResponse
        //private InitiateSessionResponse instance;

        public InitiateSessionResponseTests()
        {
            // TODO uncomment below to create an instance of InitiateSessionResponse
            //instance = new InitiateSessionResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InitiateSessionResponse
        /// </summary>
        [Fact]
        public void InitiateSessionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" InitiateSessionResponse
            //Assert.IsType<InitiateSessionResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }

        /// <summary>
        /// Test the property 'CheckoutFrontendUrl'
        /// </summary>
        [Fact]
        public void CheckoutFrontendUrlTest()
        {
            // TODO unit test for the property 'CheckoutFrontendUrl'
        }

        /// <summary>
        /// Test the property 'PollingUrl'
        /// </summary>
        [Fact]
        public void PollingUrlTest()
        {
            // TODO unit test for the property 'PollingUrl'
        }
    }
}
