/*
 * checkout-backend-merchant-v3.API
 *
 * See the [Checkout API Guide](https://developer.vippsmobilepay.com/docs/APIs/checkout-api/).
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Checkout.Model;
using Vipps.net.Models.Checkout.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Checkout.Test.Model
{
    /// <summary>
    ///  Class for testing InitiatePaymentSessionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InitiatePaymentSessionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InitiatePaymentSessionRequest
        //private InitiatePaymentSessionRequest instance;

        public InitiatePaymentSessionRequestTests()
        {
            // TODO uncomment below to create an instance of InitiatePaymentSessionRequest
            //instance = new InitiatePaymentSessionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InitiatePaymentSessionRequest
        /// </summary>
        [Fact]
        public void InitiatePaymentSessionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" InitiatePaymentSessionRequest
            //Assert.IsType<InitiatePaymentSessionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Transaction'
        /// </summary>
        [Fact]
        public void TransactionTest()
        {
            // TODO unit test for the property 'Transaction'
        }

        /// <summary>
        /// Test the property 'Logistics'
        /// </summary>
        [Fact]
        public void LogisticsTest()
        {
            // TODO unit test for the property 'Logistics'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'PrefillCustomer'
        /// </summary>
        [Fact]
        public void PrefillCustomerTest()
        {
            // TODO unit test for the property 'PrefillCustomer'
        }

        /// <summary>
        /// Test the property 'MerchantInfo'
        /// </summary>
        [Fact]
        public void MerchantInfoTest()
        {
            // TODO unit test for the property 'MerchantInfo'
        }

        /// <summary>
        /// Test the property 'VarConfiguration'
        /// </summary>
        [Fact]
        public void VarConfigurationTest()
        {
            // TODO unit test for the property 'VarConfiguration'
        }
    }
}
