/*
 * checkout-backend-merchant-v3.API
 *
 * See the [Checkout API Guide](https://developer.vippsmobilepay.com/docs/APIs/checkout-api/).
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Checkout.Model;
using Vipps.net.Models.Checkout.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Checkout.Test.Model
{
    /// <summary>
    ///  Class for testing IntervalUnit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IntervalUnitTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IntervalUnit
        //private IntervalUnit instance;

        public IntervalUnitTests()
        {
            // TODO uncomment below to create an instance of IntervalUnit
            //instance = new IntervalUnit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IntervalUnit
        /// </summary>
        [Fact]
        public void IntervalUnitInstanceTest()
        {
            // TODO uncomment below to test "IsType" IntervalUnit
            //Assert.IsType<IntervalUnit>(instance);
        }
    }
}
