/*
 * checkout-backend-merchant-v3.API
 *
 * See the [Checkout API Guide](https://developer.vippsmobilepay.com/docs/APIs/checkout-api/).
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Checkout.Model;
using Vipps.net.Models.Checkout.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Checkout.Test.Model
{
    /// <summary>
    ///  Class for testing MerchantInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MerchantInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MerchantInfo
        //private MerchantInfo instance;

        public MerchantInfoTests()
        {
            // TODO uncomment below to create an instance of MerchantInfo
            //instance = new MerchantInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MerchantInfo
        /// </summary>
        [Fact]
        public void MerchantInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" MerchantInfo
            //Assert.IsType<MerchantInfo>(instance);
        }

        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Fact]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }

        /// <summary>
        /// Test the property 'ReturnUrl'
        /// </summary>
        [Fact]
        public void ReturnUrlTest()
        {
            // TODO unit test for the property 'ReturnUrl'
        }

        /// <summary>
        /// Test the property 'CallbackAuthorizationToken'
        /// </summary>
        [Fact]
        public void CallbackAuthorizationTokenTest()
        {
            // TODO unit test for the property 'CallbackAuthorizationToken'
        }

        /// <summary>
        /// Test the property 'TermsAndConditionsUrl'
        /// </summary>
        [Fact]
        public void TermsAndConditionsUrlTest()
        {
            // TODO unit test for the property 'TermsAndConditionsUrl'
        }
    }
}
