/*
 * checkout-backend-merchant-v3.API
 *
 * See the [Checkout API Guide](https://developer.vippsmobilepay.com/docs/APIs/checkout-api/).
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Checkout.Model;
using Vipps.net.Models.Checkout.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Checkout.Test.Model
{
    /// <summary>
    ///  Class for testing OrderBottomLine
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderBottomLineTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderBottomLine
        //private OrderBottomLine instance;

        public OrderBottomLineTests()
        {
            // TODO uncomment below to create an instance of OrderBottomLine
            //instance = new OrderBottomLine();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderBottomLine
        /// </summary>
        [Fact]
        public void OrderBottomLineInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderBottomLine
            //Assert.IsType<OrderBottomLine>(instance);
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'TipAmount'
        /// </summary>
        [Fact]
        public void TipAmountTest()
        {
            // TODO unit test for the property 'TipAmount'
        }

        /// <summary>
        /// Test the property 'GiftCardAmount'
        /// </summary>
        [Fact]
        public void GiftCardAmountTest()
        {
            // TODO unit test for the property 'GiftCardAmount'
        }

        /// <summary>
        /// Test the property 'TerminalId'
        /// </summary>
        [Fact]
        public void TerminalIdTest()
        {
            // TODO unit test for the property 'TerminalId'
        }

        /// <summary>
        /// Test the property 'PaymentSources'
        /// </summary>
        [Fact]
        public void PaymentSourcesTest()
        {
            // TODO unit test for the property 'PaymentSources'
        }

        /// <summary>
        /// Test the property 'ReceiptNumber'
        /// </summary>
        [Fact]
        public void ReceiptNumberTest()
        {
            // TODO unit test for the property 'ReceiptNumber'
        }
    }
}
