/*
 * checkout-backend-merchant-v3.API
 *
 * See the [Checkout API Guide](https://developer.vippsmobilepay.com/docs/APIs/checkout-api/).
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Checkout.Model;
using Vipps.net.Models.Checkout.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Checkout.Test.Model
{
    /// <summary>
    ///  Class for testing OrderUnitInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderUnitInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderUnitInfo
        //private OrderUnitInfo instance;

        public OrderUnitInfoTests()
        {
            // TODO uncomment below to create an instance of OrderUnitInfo
            //instance = new OrderUnitInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderUnitInfo
        /// </summary>
        [Fact]
        public void OrderUnitInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderUnitInfo
            //Assert.IsType<OrderUnitInfo>(instance);
        }

        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Fact]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'QuantityUnit'
        /// </summary>
        [Fact]
        public void QuantityUnitTest()
        {
            // TODO unit test for the property 'QuantityUnit'
        }
    }
}
