/*
 * checkout-backend-merchant-v3.API
 *
 * See the [Checkout API Guide](https://developer.vippsmobilepay.com/docs/APIs/checkout-api/).
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Checkout.Model;
using Vipps.net.Models.Checkout.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Checkout.Test.Model
{
    /// <summary>
    ///  Class for testing OtherLogisticsOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OtherLogisticsOptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OtherLogisticsOption
        //private OtherLogisticsOption instance;

        public OtherLogisticsOptionTests()
        {
            // TODO uncomment below to create an instance of OtherLogisticsOption
            //instance = new OtherLogisticsOption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OtherLogisticsOption
        /// </summary>
        [Fact]
        public void OtherLogisticsOptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" OtherLogisticsOption
            //Assert.IsType<OtherLogisticsOption>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'TaxRate'
        /// </summary>
        [Fact]
        public void TaxRateTest()
        {
            // TODO unit test for the property 'TaxRate'
        }

        /// <summary>
        /// Test the property 'Brand'
        /// </summary>
        [Fact]
        public void BrandTest()
        {
            // TODO unit test for the property 'Brand'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }

        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Fact]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
