/*
 * checkout-backend-merchant-v3.API
 *
 * See the [Checkout API Guide](https://developer.vippsmobilepay.com/docs/APIs/checkout-api/).
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Checkout.Model;
using Vipps.net.Models.Checkout.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Checkout.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentState
        //private PaymentState instance;

        public PaymentStateTests()
        {
            // TODO uncomment below to create an instance of PaymentState
            //instance = new PaymentState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentState
        /// </summary>
        [Fact]
        public void PaymentStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentState
            //Assert.IsType<PaymentState>(instance);
        }
    }
}
