/*
 * checkout-backend-merchant-v3.API
 *
 * See the [Checkout API Guide](https://developer.vippsmobilepay.com/docs/APIs/checkout-api/).
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vipps.net.Models.Checkout.Model;
using Vipps.net.Models.Checkout.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vipps.net.Models.Checkout.Test.Model
{
    /// <summary>
    ///  Class for testing ResponseCardPaymentDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseCardPaymentDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResponseCardPaymentDetails
        //private ResponseCardPaymentDetails instance;

        public ResponseCardPaymentDetailsTests()
        {
            // TODO uncomment below to create an instance of ResponseCardPaymentDetails
            //instance = new ResponseCardPaymentDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResponseCardPaymentDetails
        /// </summary>
        [Fact]
        public void ResponseCardPaymentDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResponseCardPaymentDetails
            //Assert.IsType<ResponseCardPaymentDetails>(instance);
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Aggregate'
        /// </summary>
        [Fact]
        public void AggregateTest()
        {
            // TODO unit test for the property 'Aggregate'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
